#include <gui/gui.h>
/* Magic happens here -- this file is generated by fbt.
 * Just set fap_icon_assets in application.fam and #include {APPID}_icons.h */
#include "pokemon_icons.h"

void draw_land(Canvas* canvas, uint32_t player_x, uint32_t player_y);
