#include <furi.h>
#include <gui/gui.h>
#include <input/input.h>
/* Magic happens here -- this file is generated by fbt.
 * Just set fap_icon_assets in application.fam and #include {APPID}_icons.h */
#include "pokemon_icons.h"

typedef enum {
    DownStale = 0, 
    DownMoving = 1,
    UpStale = 2,
    UpMoving = 3,
    LeftStale = 4,
    LeftMoving = 5,
    RightStale = 6,
    RightMoving = 7
} PlayerMovement;

typedef struct {
    PlayerMovement movement;
    const uint32_t x;
    const uint32_t y;
} Player;
 
void draw_player(Canvas* canvas, Player* player);

void handle_player_movement(InputEvent event, Player* player);
